#!/bin/sh  
echo ...compling $1.s
#clear
#as   -gstabs -o $1.o   $1.s
 as  -g -o $1.o   $1.s
#ld -m elf_x86_64  -dynamic-linker /lib64/ld-linux.so.2 -lc  -o $1 $1.o
#ld -m elf_x86_64  -dynamic-linking /lib/ld-linux.so.2 -lc  -o $1 $1.o
ld  -dynamic-linker  /lib64/ld-linux-x86-64.so.2 -lc  -o $1 $1.o
echo ...done!